import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Motorola dataScrubTool",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                {/* Link tag for the favicon */}
                <link rel="icon" href="/favicon.ico" type="image/x-icon" />
            </head>
            <body className={inter.className}>
                {children}
                <footer className="bg-gray-800 p-4 text-white text-center">
                    <p>&copy; 2024 juic3b0x. All rights reserved.</p>
                    <p>
                        MOTOROLA, the Stylized M Logo, MOTO, and the MOTO family
                        of marks are trademarks of Motorola Trademark Holdings,
                        LLC. LENOVO is a trademark of Lenovo. All other
                        trademarks are the property of their respective owners.
                    </p>
                </footer>
                <SpeedInsights />
                <Analytics />
                <SpeedInsights />
            </body>
        </html>
    );
}
